/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments.$deploymentId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'
import { Route as ResultsResultIdRouteImport } from './routes/results.$resultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => BatchesRoute,
} as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/$deploymentId',
  path: '/$deploymentId',
  getParentRoute: () => DeploymentsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => ModelsRoute,
} as any)
const ResultsResultIdRoute = ResultsResultIdRouteImport.update({
  id: '/$resultId',
  path: '/$resultId',
  getParentRoute: () => ResultsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/api-reference': typeof ApiReferenceRoute
  '/audit-log': typeof AuditLogRoute
  '/batches': typeof BatchesRouteWithChildren
  '/benchmarks': typeof BenchmarksRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/models': typeof ModelsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/results': typeof ResultsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/system-health': typeof SystemHealthRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/api-reference': typeof ApiReferenceRoute
  '/audit-log': typeof AuditLogRoute
  '/batches': typeof BatchesRouteWithChildren
  '/benchmarks': typeof BenchmarksRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/models': typeof ModelsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/results': typeof ResultsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/system-health': typeof SystemHealthRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/api-reference': typeof ApiReferenceRoute
  '/audit-log': typeof AuditLogRoute
  '/batches': typeof BatchesRouteWithChildren
  '/benchmarks': typeof BenchmarksRoute
  '/deployments': typeof DeploymentsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/models': typeof ModelsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/results': typeof ResultsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/system-health': typeof SystemHealthRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/webhooks': typeof WebhooksRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/results/$resultId': typeof ResultsResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/api-reference'
    | '/audit-log'
    | '/batches'
    | '/benchmarks'
    | '/deployments'
    | '/jobs'
    | '/metrics'
    | '/models'
    | '/playground'
    | '/results'
    | '/settings'
    | '/storage'
    | '/system-health'
    | '/team'
    | '/usage'
    | '/webhooks'
    | '/batches/$batchId'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/models/$modelId'
    | '/results/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/api-reference'
    | '/audit-log'
    | '/batches'
    | '/benchmarks'
    | '/deployments'
    | '/jobs'
    | '/metrics'
    | '/models'
    | '/playground'
    | '/results'
    | '/settings'
    | '/storage'
    | '/system-health'
    | '/team'
    | '/usage'
    | '/webhooks'
    | '/batches/$batchId'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/models/$modelId'
    | '/results/$resultId'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/api-reference'
    | '/audit-log'
    | '/batches'
    | '/benchmarks'
    | '/deployments'
    | '/jobs'
    | '/metrics'
    | '/models'
    | '/playground'
    | '/results'
    | '/settings'
    | '/storage'
    | '/system-health'
    | '/team'
    | '/usage'
    | '/webhooks'
    | '/batches/$batchId'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/models/$modelId'
    | '/results/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  AuditLogRoute: typeof AuditLogRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  BenchmarksRoute: typeof BenchmarksRoute
  DeploymentsRoute: typeof DeploymentsRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  MetricsRoute: typeof MetricsRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  ResultsRoute: typeof ResultsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  SystemHealthRoute: typeof SystemHealthRoute
  TeamRoute: typeof TeamRoute
  UsageRoute: typeof UsageRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof DeploymentsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/results/$resultId': {
      id: '/results/$resultId'
      path: '/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdRouteImport
      parentRoute: typeof ResultsRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesBatchIdRoute: BatchesBatchIdRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

interface DeploymentsRouteChildren {
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
}

const DeploymentsRouteChildren: DeploymentsRouteChildren = {
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
}

const DeploymentsRouteWithChildren = DeploymentsRoute._addFileChildren(
  DeploymentsRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface ModelsRouteChildren {
  ModelsModelIdRoute: typeof ModelsModelIdRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsModelIdRoute: ModelsModelIdRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface ResultsRouteChildren {
  ResultsResultIdRoute: typeof ResultsResultIdRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsResultIdRoute: ResultsResultIdRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  AuditLogRoute: AuditLogRoute,
  BatchesRoute: BatchesRouteWithChildren,
  BenchmarksRoute: BenchmarksRoute,
  DeploymentsRoute: DeploymentsRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  MetricsRoute: MetricsRoute,
  ModelsRoute: ModelsRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  ResultsRoute: ResultsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  SystemHealthRoute: SystemHealthRoute,
  TeamRoute: TeamRoute,
  UsageRoute: UsageRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
